services:
  wan-gguf:
    build: .
    command: python app.py
    ports:
      - "7861:7861"
    volumes:
      # Storage no Windows - Docker Desktop gerencia automaticamente
      - /mnt/e/Docker/wan/wan-gguf/models:/app/models
      - /mnt/e/Docker/wan/wan-gguf/cache:/root/.cache/huggingface
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HF_TOKEN:-}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - GRADIO_SERVER_PORT=7861
      - PYTHONUNBUFFERED=1
      - HF_HOME=/app/models  # Usar apenas HF_HOME (não TRANSFORMERS_CACHE)
      - CUDA_VISIBLE_DEVICES=0  # Forçar uso da primeira GPU
      - TORCH_CUDA_ARCH_LIST="8.6"  # RTX 3060 architecture
    restart: unless-stopped
    # GPU passthrough via Docker Desktop
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # Configurações para Docker Desktop
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
